# Generated by Django 6.0.8 on 2026-08-18 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        # The schema is not created by `migrate`; doing it here keeps a fresh
        # database (and CI) working without a manual step.
        migrations.RunSQL(
            f'CREATE SCHEMA IF NOT EXISTS "{settings.DB_SCHEMA}"',
            migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(default="accueil", unique=True, verbose_name="identifiant")),
                ("label", models.CharField(default="Accueil", max_length=120, verbose_name="nom")),
            ],
            options={
                "verbose_name": "page",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(max_length=40, verbose_name="type de section")),
                ("position", models.PositiveIntegerField(verbose_name="ordre")),
                ("active", models.BooleanField(default=True, verbose_name="affichée")),
                ("content", models.JSONField(blank=True, default=dict, verbose_name="écarts au texte du code")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="accueil.page"
                    ),
                ),
            ],
            options={
                "verbose_name": "section",
                "ordering": ["position"],
                "constraints": [models.UniqueConstraint(fields=("page", "kind"), name="unique_kind_per_page")],
            },
        ),
    ]
